// data.js - central content store
window.CIPHER_DATA = {
  ticker: [
    { tag: '[ALERT]',      tagClass: 'tag-alert',  text: 'Critical zero-day in OpenSSH - patch immediately' },
    { tag: '[CVE]',        tagClass: 'tag-cve',    text: 'CVE-2024-11881 - CVSS 9.8 - Remote Code Execution' },
    { tag: '[BREACH]',     tagClass: 'tag-breach', text: 'Cloud provider reports unauthorized access to 1.2M records' },
    { tag: '[TIP]',        tagClass: 'tag-tip',    text: 'Enable MFA on all privileged accounts immediately' },
    { tag: '[RESEARCH]',   tagClass: 'tag-cve',    text: 'New side-channel attack bypasses hardware encryption' },
    { tag: '[RANSOMWARE]', tagClass: 'tag-breach', text: 'LockBit variant targeting healthcare sector detected' },
    { tag: '[TOOL]',       tagClass: 'tag-tool',   text: 'Wireshark 4.2 released with improved protocol dissectors' },
    { tag: '[ADVISORY]',   tagClass: 'tag-alert',  text: 'CISA adds 3 new vulnerabilities to known exploited list' },
    { tag: '[PATCH]',      tagClass: 'tag-tip',    text: 'Microsoft Patch Tuesday: 67 fixes, 6 critical RCE' },
  ],
  topics: [
    {
      num: '01', icon: '🛡️',
      title: 'Network Defense',
      desc: 'Firewalls, IDS/IPS, segmentation strategies, traffic analysis, and building resilient network architectures against modern threats.',
      tag: 'Defensive',
    },
    {
      num: '02', icon: '🔴',
      title: 'Red Team Ops',
      desc: 'Penetration testing methodologies, lateral movement, privilege escalation, C2 frameworks, and adversary simulation techniques.',
      tag: 'Offensive',
    },
    {
      num: '03', icon: '🔐',
      title: 'Cryptography',
      desc: 'Symmetric and asymmetric encryption, PKI, TLS internals, hash functions, and identifying weak implementations in the wild.',
      tag: 'Foundations',
    },
    {
      num: '04', icon: '🕵️',
      title: 'Threat Intelligence',
      desc: 'OSINT techniques, threat actor profiling, IOC analysis, MITRE ATT&CK framework mapping, and structured threat hunting workflows.',
      tag: 'Intelligence',
    },
    {
      num: '05', icon: '🧩',
      title: 'Malware Analysis',
      desc: 'Static and dynamic analysis, reverse engineering with Ghidra/IDA, sandbox environments, deobfuscation, and writing YARA rules.',
      tag: 'Forensics',
    },
    {
      num: '06', icon: '☁️',
      title: 'Cloud Security',
      desc: 'AWS/Azure/GCP misconfigurations, IAM privilege escalation, container escape, serverless attack surfaces, and CSPM tooling.',
      tag: 'Cloud',
    },
  ],
  articles: [
    {
      id: 1,
      featured: true,
      category: 'critical',
      badge: 'Critical',
      badgeClass: 'badge-red',
      title: 'Anatomy of a Supply Chain Attack: How SolarWinds Changed Everything',
      excerpt: 'A deep technical analysis of how nation-state actors compromised a software build pipeline and silently infected 18,000 organizations - and what defenders can learn.',
      body: 'Understanding the SUNBURST implant, its C2 communication patterns, and the detection gaps that allowed it to operate undetected for nine months.',
      date: '2024-12-01',
      readTime: '18 MIN',
      tag: 'SUPPLY CHAIN',
    },
    {
      id: 2,
      featured: false,
      category: 'research',
      badge: 'Research',
      badgeClass: 'badge-cyan',
      title: 'Bypassing EDR With Direct Syscalls',
      excerpt: 'How attackers evade endpoint detection by calling Windows kernel functions directly, skipping userland hooks entirely.',
      date: '2024-11-20',
      readTime: '9 MIN',
      tag: 'EVASION',
    },
    {
      id: 3,
      featured: false,
      category: 'tutorial',
      badge: 'Tutorial',
      badgeClass: 'badge-green',
      title: 'Building a Home SOC for Under $200',
      excerpt: 'Set up a fully functional security operations center with open-source tools on commodity hardware.',
      date: '2024-11-14',
      readTime: '12 MIN',
      tag: 'BLUE TEAM',
    },
    {
      id: 4,
      featured: false,
      category: 'malware',
      badge: 'Malware',
      badgeClass: 'badge-red',
      title: 'Dissecting a New Infostealer Targeting Crypto Wallets',
      excerpt: 'Static and dynamic analysis of a novel Python-based stealer with browser injection capabilities.',
      date: '2024-11-08',
      readTime: '14 MIN',
      tag: 'REVERSE ENG',
    },
    {
      id: 5,
      featured: false,
      category: 'research',
      badge: 'Guide',
      badgeClass: 'badge-cyan',
      title: 'OSINT Tradecraft: Tracking Infrastructure Without Getting Burned',
      excerpt: 'Operational security for threat researchers - how to investigate without leaving fingerprints.',
      date: '2024-11-01',
      readTime: '10 MIN',
      tag: 'OSINT',
    },
  ],
  terminal: [
    { type: 'comment', text: '# Nmap service detection scan' },
    { type: 'cmd',  prompt: true, text: 'nmap -sV -sC -T4 10.0.0.1' },
    { type: 'out',  text: 'Starting Nmap 7.94 ( https://nmap.org )' },
    { type: 'out',  text: 'Nmap scan report for 10.0.0.1' },
    { type: 'out',  text: 'Host is up (0.0031s latency).' },
    { type: 'blank' },
    { type: 'out',  text: 'PORT     STATE SERVICE    VERSION' },
    { type: 'out',  text: '─────────────────────────────────────' },
    { type: 'ok',   text: '22/tcp   open  ssh        OpenSSH 8.9p1' },
    { type: 'warn', text: '80/tcp   open  http       Apache httpd 2.4.52' },
    { type: 'err',  text: '3306/tcp open  mysql      MySQL 5.7.39' },
    { type: 'blank' },
    { type: 'err',  text: '[!] WARNING: MySQL port exposed - no auth required' },
    { type: 'warn', text: '[~] Apache version may be outdated (CVE-2022-31813)' },
    { type: 'blank' },
    { type: 'comment', text: '# Nmap done: 1 IP address scanned in 4.21s' },
    { type: 'blank' },
    { type: 'cursor' },
  ],
  searchIndex: [
    { title: 'Network Defense', tag: 'TOPIC', href: '#topics' },
    { title: 'Red Team Operations', tag: 'TOPIC', href: '#topics' },
    { title: 'Cryptography Fundamentals', tag: 'TOPIC', href: '#topics' },
    { title: 'Threat Intelligence & OSINT', tag: 'TOPIC', href: '#topics' },
    { title: 'Malware Analysis', tag: 'TOPIC', href: '#topics' },
    { title: 'Cloud Security (AWS/Azure/GCP)', tag: 'TOPIC', href: '#topics' },
    { title: 'SolarWinds Supply Chain Attack', tag: 'ARTICLE', href: '#intel' },
    { title: 'Bypassing EDR with Direct Syscalls', tag: 'ARTICLE', href: '#intel' },
    { title: 'Building a Home SOC', tag: 'ARTICLE', href: '#intel' },
    { title: 'Infostealer Malware Analysis', tag: 'ARTICLE', href: '#intel' },
    { title: 'OSINT Tradecraft Guide', tag: 'ARTICLE', href: '#intel' },
    { title: 'Lab Environment', tag: 'LAB', href: '#learn' },
    { title: 'Weekly Intel Newsletter', tag: 'COMMUNITY', href: '#community' },
    { title: 'IP Address Analyser', tag: 'TOOL', href: '#scanner' },
    { title: 'CIDR Subnet Calculator', tag: 'TOOL', href: '#scanner' },
    { title: 'Detect My Public IP', tag: 'TOOL', href: '#scanner' },
    { title: 'Network Scanner Tool', tag: 'TOOL', href: '#scanner' },
    { title: 'CVE Database', tag: 'RESOURCE', href: '#intel' },
    { title: 'MITRE ATT&CK Framework', tag: 'RESOURCE', href: '#topics' },
  ],
};
